insert into login (id, usuario, senha) values(1,'José Ricardo', '1234');
insert into login (id, usuario, senha) values(2,'Jessica Brito', '5678');
insert into login (id, usuario, senha) values(3,'Camila', '9090');

insert into autor (nome, biografia) values('Colleen Hoover', 'Colleen Hoover é uma escritora norte-americana que escreve principalmente romances nos gêneros romântico e ficção para jovens adultos. Muitos de seus trabalhos foram autopublicados antes de serem adquiridos por uma editora.');
insert into autor (nome, biografia) values('Ali Hazelwood', 'Ali Hazelwood é uma autora norte-americana. Ela escreve principalmente romances contemporâneos, com foco em narrativas de amor e relacionamentos. Suas obras são conhecidas por apresentar personagens autênticos e envolventes, explorando temas como crescimento pessoal, resiliência e a complexidade das emoções humanas.');
insert into autor (nome, biografia) values('Augusto Cury', 'Augusto Cury é um renomado psiquiatra, psicoterapeuta, cientista e escritor brasileiro. Ele é autor de diversos best-sellers que exploram temas relacionados à psicologia, autoajuda e desenvolvimento pessoal. Cury é conhecido por sua abordagem inovadora no estudo da mente humana e suas obras oferecem insights valiosos sobre como lidar com questões emocionais, desenvolver a inteligência emocional e alcançar uma vida mais plena e equilibrada.');

insert into livro (titulo, id_autor, editora, genero, preco, quantidadeEstoque, isbn, dataLancamento, dateCadastro, descricao) values ('O Lado Feio do Amor', 1, 'Galera Record', 'Romance', 29.90, 50, 9788501084045, '2015-09-01', '2024-03-04', 'Um romance cativante que explora os altos e baixos do amor.');
insert into livro (titulo, id_autor, editora, genero, preco, quantidadeEstoque, isbn, dataLancamento, dateCadastro, descricao) values ('A Hipótese do Amor', 2, 'Intrínseca', 'Romance', 39.90, 30, 9786555602457, '2021-10-01', '2024-03-04', 'Uma história envolvente sobre amor e autodescoberta.');
insert into livro (titulo, id_autor, editora, genero, preco, quantidadeEstoque, isbn, dataLancamento, dateCadastro, descricao) values ('O Vendedor de Sonhos', 3, 'Editora Sextante', 'Autoajuda', 34.90, 40, 9788543104809, '2016-01-01', '2024-03-04', 'Um livro inspirador que nos convida a refletir sobre o verdadeiro sentido da vida.');